[build]
publish = "."

[[redirects]]
from = "/adminsupremo"
to = "/adminsupremo.html"
status = 200
force = false

[[redirects]]
from = "/api/ironpay/*"
to = "https://api.ironpayapp.com.br/api/public/v1/:splat"
status = 200
force = true
  [redirects.headers]
  Content-Type = "application/json"

[[redirects]]
from = "/api/xpag/*"
to = "https://api.xpag.global/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
